apiVersion: "security.istio.io/v1beta1"
kind: AuthorizationPolicy
metadata:
  name: authenticated-api
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  rules:
      - from:
        - source:
            requestPrincipals: ["*"]
        to:
        - operation:
            methods: ["GET"]
            paths: ["/anything/api/authenticated*"]
            hosts: ["httpbin.io"]
  action: ALLOW