apiVersion: "security.istio.io/v1beta1"
kind: AuthorizationPolicy
metadata:
  name: allow-ingress-gateway-to-access-httpbin
  namespace: istioinaction
spec:
  selector:
    matchLabels:
      app: httpbin
  rules:
    - from:
        - source: # TODO check capabilities in Spring Cloud that we can't do in ingressgateway - replace one with the other?
            principals: ["cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"]
#      to:
#        - operation:
#            hosts: ["httpbin.io"]