apiVersion: "security.istio.io/v1beta1"
kind: AuthorizationPolicy
metadata:
  name: allow-all-ingress
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  rules:
    - {} # allow all if empty rule
#       i want to allow everyone through the
#      ingress gateway, then deny everyone later per service
# I think this is the wrong way to do it, you should do everything at the ingress level with hosts instead! like in
# ap-allow-all-to-ROLE_AXIS_ADMIN-ingress-level.yaml
